# Generated by Django 5.1.7 on 2025-03-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_categoria_alter_produto_imagem_alter_produto_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desenvolvedor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='distribuidor',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='lancamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
