# Generated by Django 5.1.7 on 2025-03-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_produto_desenvolvedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(null=True, related_name='produtos', to='loja.categoria'),
        ),
    ]
